version: "3.9"

services:
  influxdb:
    image: influxdb:2.1.1
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DOCKER_INFLUXDB_INIT_USERNAME=waggle
      - DOCKER_INFLUXDB_INIT_PASSWORD=wagglewaggle
      - DOCKER_INFLUXDB_INIT_ORG=waggle
      - DOCKER_INFLUXDB_INIT_BUCKET=waggle
      # NOTE(sean) This token is assumed to be public and should only be used for local testing!
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=zFloIAmPQExH5UL462zl5KsmYE9XBmgT7AU88txHoHm7YnI8MSN14Q==

  rabbitmq:
    image: rabbitmq:3.8.11-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json

  loader:
    build: ..
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - INFLUXDB_TOKEN=zFloIAmPQExH5UL462zl5KsmYE9XBmgT7AU88txHoHm7YnI8MSN14Q==
    restart: always
